import Foundation
import Network
import XCTest

/// Physical-only black-box coverage for the exact Release app.
///
/// This test deliberately gives the app no launch arguments or environment.
/// Configuration is performed through shipped controls, and packet evidence is
/// generated by this separate XCTest runner so app-internal probes cannot make
/// a broken production tunnel pass.
final class NostrVpnReleaseNetworkUITests: XCTestCase {
    struct Spec: Decodable {
        let runId: String
        let caseName: String
        let networkName: String
        let wireGuardConfig: String
        let mode: String
        let provider: String
        let customUrl: String
        let bootstrapIps: String
        let throughExitServers: String
        let resolverQueryHost: String
        let resolverProbeUrl: String
        let resolverExpectedBody: String?
        let udpHost: String
        let udpPort: UInt16
        let publicHttpsUrl: String
        let sourceIpUrl: String
        let expectedExitSourceIp: String
        let createNetwork: Bool
        let exerciseStartStopStress: Bool
        let exerciseUnderlay: Bool
        let exerciseLifecycle: Bool
        let switchToDirect: Bool
        let lifecycleCycles: Int
        let backgroundDwellSeconds: Int
        let underlayAssociationTimeoutSeconds: Int
    }

    let app = XCUIApplication()

    override func setUpWithError() throws {
        continueAfterFailure = false
        PhysicalGateMarker.reset()
    }

    func testReleaseNetworkLifecycle() throws {
        let spec = try releaseSpec()
        try validate(spec)
        XCTAssertTrue(app.launchArguments.isEmpty)
        XCTAssertTrue(app.launchEnvironment.isEmpty)
        emit("NVPN_IOS_RELEASE_RUN_ID=\(spec.runId)")

        app.launch()
        XCTAssertTrue(waitForApplicationState(.runningForeground, timeout: 10))
        XCTAssertTrue(app.windows.firstMatch.waitForExistence(timeout: 5))
        try ensureNetwork(spec)
        let autoconnectWasEnabled = try setStartVpnAutomatically(false)
        addTeardownBlock { [weak self] in
            guard let self else { return }
            _ = try self.setStartVpnAutomatically(autoconnectWasEnabled)
        }
        try turnVPNOffIfNeeded()

        try NostrVpnReleaseNetworkProbe.requirePublicHTTPS(spec.publicHttpsUrl)
        let directSource = try waitForSourceIP(
            spec.sourceIpUrl,
            timeout: 15
        )
        try NostrVpnReleaseNetworkProbe.requireControlledHTTPUnavailable(
            spec.resolverProbeUrl
        )
        emit("NVPN_IOS_RELEASE_DIRECT_BEFORE_PASSED=1")

        try configureWireGuard(spec)
        try configureExitDNS(spec)

        if spec.exerciseStartStopStress {
            try driveRapidStartStopStress(spec, directSource: directSource)
        }
        try turnVPNOn()
        try waitForSourceIP(
            spec.sourceIpUrl,
            expected: spec.expectedExitSourceIp,
            timeout: 20
        )
        emit("NVPN_IOS_RELEASE_ACTIVE_SESSION_BEGIN_MS=\(millisecondsSinceEpoch())")
        try proveExit(spec, label: "connected")
        if spec.exerciseStartStopStress {
            emit("NVPN_IOS_RELEASE_START_STOP_RECOVERED=1")
        }
        emit("NVPN_IOS_RELEASE_EXIT_CONNECTED=\(spec.caseName)")

        if spec.exerciseUnderlay {
            try driveUnderlayChanges(spec)
        }
        if spec.exerciseLifecycle {
            try driveBackgroundForeground(spec)
            try driveConfigSyncBackgroundForeground(spec, directSource: directSource)
        }
        if spec.switchToDirect {
            try selectDirectWhileConnected(spec, directSource: directSource)
        }

        emit("NVPN_IOS_RELEASE_ACTIVE_SESSION_END_MS=\(millisecondsSinceEpoch())")
        // Keep the production packet tunnel alive while the external process
        // sampler records the final active-session checkpoint.
        Thread.sleep(forTimeInterval: 6)
        try turnVPNOffIfNeeded()
        relaunch()
        guard waitForVPNState(on: false, timeout: 15) else {
            throw gateError("Release app relaunched with a stale packet tunnel after VPN off")
        }
        try proveDirect(spec, expectedSource: directSource)
        emit("NVPN_IOS_RELEASE_DIRECT_AFTER_PASSED=1")
        emit("NVPN_IOS_RELEASE_NETWORK_PASSED=\(spec.caseName)")
    }

    func testReleaseDisconnectCleanup() throws {
        XCTAssertEqual(
            ProcessInfo.processInfo.environment["NVPN_XCUITEST_RELEASE_NETWORK_GATE"],
            "1"
        )
        XCTAssertTrue(app.launchArguments.isEmpty)
        XCTAssertTrue(app.launchEnvironment.isEmpty)
        app.launch()
        XCTAssertTrue(waitForApplicationState(.runningForeground, timeout: 10))
        if let spec = optionalReleaseSpec(), spec.exerciseUnderlay {
            let originalSsid = try originalWiFiForCleanup()
            try setWiFiEnabled(true)
            guard waitForPhysicalPath(
                required: .wifi,
                excluded: .cellular,
                timeout: TimeInterval(spec.underlayAssociationTimeoutSeconds)
            ) != nil,
                try selectedWiFiSSID() == originalSsid
            else {
                throw gateError("Cleanup did not restore the exact original Wi-Fi")
            }
            try clearOriginalWiFiCleanup()
            app.activate()
            XCTAssertTrue(waitForApplicationState(.runningForeground, timeout: 10))
            emit("NVPN_IOS_RELEASE_HOME_WIFI_RESTORED=1")
        }
        if app.tabBars.buttons["Devices"].waitForExistence(timeout: 3) {
            try turnVPNOffIfNeeded()
        }
        if let spec = optionalReleaseSpec() {
            try NostrVpnReleaseNetworkProbe.requirePublicHTTPS(spec.publicHttpsUrl)
            _ = try waitForSourceIP(
                spec.sourceIpUrl,
                timeout: 15
            )
            try NostrVpnReleaseNetworkProbe.requireControlledHTTPUnavailable(
                spec.resolverProbeUrl
            )
        }
        emit("NVPN_IOS_RELEASE_DISCONNECT_PASSED=1")
    }

    private func ensureNetwork(_ spec: Spec) throws {
        if app.tabBars.buttons["Internet"].waitForExistence(timeout: 3) {
            return
        }
        guard spec.createNetwork else {
            throw gateError("Release app has no network and this case may not create one")
        }
        let createChoice = element("network-setup-create")
        guard createChoice.waitForExistence(timeout: 8), createChoice.isHittable else {
            throw gateError("Shipped Create Network control was unavailable")
        }
        let name = element("network-create-name")
        guard ShippedUIInteraction.reveal(name, byTapping: createChoice) else {
            throw gateError(
                "Shipped Create Network control did not reveal the network-name field"
            )
        }
        replaceText(name, with: spec.networkName)
        let submit = scrollToElement("network-create-submit")
        guard submit.isEnabled, submit.isHittable else {
            throw gateError("Shipped Create button was disabled")
        }
        submit.tap()
        acknowledgeVPNPrompts(timeout: 8)
        guard app.tabBars.buttons["Internet"].waitForExistence(timeout: 20) else {
            throw gateError("Network creation did not reach the production app shell")
        }
        emit("NVPN_IOS_RELEASE_NETWORK_CREATED=1")
    }

    private func configureWireGuard(_ spec: Spec) throws {
        openInternetTab()
        selectMenu(
            picker: "internet-source-picker",
            option: "internet-source-wireguard"
        )

        let editor = scrollToElement("wireguard-config")
        replaceText(editor, with: spec.wireGuardConfig)
        let save = scrollToElement("wireguard-save")
        guard save.isEnabled, save.isHittable else {
            throw gateError("Shipped WireGuard Save button was disabled")
        }
        save.tap()
        waitForActionToSettle()

        let toggle = scrollToElement("wireguard-enabled")
        if !wireGuardIsOn(toggle) {
            toggle.tap()
            waitForActionToSettle()
        }
        guard wireGuardIsOn(scrollToElement("wireguard-enabled")) else {
            throw gateError("Shipped WireGuard toggle did not remain enabled")
        }

        relaunch()
        openInternetTab()
        assertPicker("internet-source-picker", contains: "WireGuard VPN")
        let persistedToggle = scrollToElement("wireguard-enabled")
        guard wireGuardIsOn(persistedToggle) else {
            throw gateError("WireGuard enabled state did not survive a real relaunch")
        }
        let persisted = enteredText(scrollToElement("wireguard-config"))
        guard persisted == spec.wireGuardConfig else {
            throw gateError("WireGuard profile did not survive a real relaunch")
        }
        emit("NVPN_IOS_RELEASE_WIREGUARD_UI_PERSISTED=1")
    }

    private func configureExitDNS(_ spec: Spec) throws {
        openInternetTab()
        switch spec.mode {
        case "automatic":
            selectMenu(
                picker: "exit-dns-mode-picker",
                option: "exit-dns-mode-automatic"
            )
        case "encrypted":
            selectMenu(
                picker: "exit-dns-mode-picker",
                option: "exit-dns-mode-encrypted"
            )
            switch spec.provider {
            case "cloudflare":
                selectMenu(
                    picker: "exit-dns-provider-picker",
                    option: "exit-dns-provider-cloudflare"
                )
            case "quad9":
                selectMenu(
                    picker: "exit-dns-provider-picker",
                    option: "exit-dns-provider-quad9"
                )
            case "custom":
                selectMenu(
                    picker: "exit-dns-provider-picker",
                    option: "exit-dns-provider-custom"
                )
                replaceText(
                    scrollToElement("exit-dns-custom-url"),
                    with: spec.customUrl
                )
                replaceText(
                    scrollToElement("exit-dns-custom-bootstrap-ips"),
                    with: spec.bootstrapIps
                )
            default:
                throw gateError("Unsupported encrypted DNS provider")
            }
        case "through_exit":
            selectMenu(
                picker: "exit-dns-mode-picker",
                option: "exit-dns-mode-through-exit"
            )
            replaceText(
                scrollToElement("exit-dns-through-exit-servers"),
                with: spec.throughExitServers
            )
        default:
            throw gateError("Unsupported Exit DNS mode")
        }

        let save = scrollToElement("exit-dns-save")
        guard save.isEnabled, save.isHittable,
              !element("exit-dns-validation-error").exists
        else {
            throw gateError("Shipped Exit DNS controls rejected the case")
        }
        save.tap()
        waitForActionToSettle()
        relaunch()
        openInternetTab()

        switch spec.mode {
        case "automatic":
            assertPicker("exit-dns-mode-picker", contains: "Automatic")
        case "encrypted":
            assertPicker("exit-dns-mode-picker", contains: "Encrypted DNS")
            let label: String
            switch spec.provider {
            case "cloudflare": label = "Cloudflare"
            case "quad9": label = "Quad9"
            case "custom": label = "Custom DoH"
            default: throw gateError("Unsupported persisted DNS provider")
            }
            assertPicker("exit-dns-provider-picker", contains: label)
            if spec.provider == "custom" {
                guard enteredText(scrollToElement("exit-dns-custom-url")) == spec.customUrl,
                      enteredText(scrollToElement("exit-dns-custom-bootstrap-ips"))
                        == spec.bootstrapIps
                else {
                    throw gateError("Custom DoH values did not survive a real relaunch")
                }
            }
        case "through_exit":
            assertPicker("exit-dns-mode-picker", contains: "DNS through exit")
            guard enteredText(scrollToElement("exit-dns-through-exit-servers"))
                    == spec.throughExitServers
            else {
                throw gateError("Through-exit DNS values did not survive a real relaunch")
            }
        default:
            throw gateError("Unsupported persisted Exit DNS mode")
        }
        guard !element("exit-dns-validation-error").exists else {
            throw gateError("Persisted Exit DNS settings became invalid")
        }
        emit("NVPN_IOS_RELEASE_DNS_UI_PERSISTED=\(spec.caseName)")
    }

    private func turnVPNOn() throws {
        let toggle = try vpnToggle()
        guard !vpnIsOn(toggle) else {
            throw gateError("Release VPN was already on before the shipped connect action")
        }
        toggle.tap()
        acknowledgeVPNPrompts(timeout: 12)
        guard waitForVPNState(on: true, timeout: 20) else {
            throw gateError("Release VPN did not turn on through its shipped control")
        }
        emit("NVPN_IOS_RELEASE_VPN_UI_ON=1")
    }

    private func turnVPNOffIfNeeded() throws {
        let toggle = try vpnToggle()
        if vpnIsOn(toggle) {
            toggle.tap()
        }
        guard waitForVPNState(on: false, timeout: 15) else {
            throw gateError("Release VPN did not turn off through its shipped control")
        }
        emit("NVPN_IOS_RELEASE_VPN_UI_OFF=1")
    }

    private func driveRapidStartStopStress(
        _ spec: Spec,
        directSource: String
    ) throws {
        let stopDelays: [TimeInterval] = [
            0,
            0.01,
            0.03,
            0.08,
            0.16,
            0.32,
            0.64,
            1,
        ]
        for (index, stopDelay) in stopDelays.enumerated() {
            let cycle = index + 1
            let startToggle = try vpnToggle()
            guard !vpnIsOn(startToggle), startToggle.isHittable else {
                throw gateError(
                    "Rapid start/stop cycle \(cycle) did not begin disconnected"
                )
            }
            startToggle.tap()
            acknowledgeVPNPrompts(timeout: 0)
            guard waitForVPNState(on: true, timeout: 2) else {
                throw gateError(
                    "Rapid start/stop cycle \(cycle) did not enter starting state"
                )
            }
            if stopDelay > 0 {
                Thread.sleep(forTimeInterval: stopDelay)
            }

            let stopToggle = try vpnToggle()
            guard vpnIsOn(stopToggle), stopToggle.isHittable else {
                throw gateError(
                    "Rapid start/stop cycle \(cycle) could not issue stop"
                )
            }
            emit(
                "NVPN_IOS_RELEASE_RAPID_STOP_REQUESTED_\(cycle)_MS="
                    + "\(millisecondsSinceEpoch())"
            )
            stopToggle.tap()
            guard waitForVPNState(on: false, timeout: 5) else {
                throw gateError(
                    "Rapid start/stop cycle \(cycle) did not stop in time"
                )
            }
            if stopDelay == 0 {
                relaunch()
                guard waitForVPNState(on: false, timeout: 5) else {
                    throw gateError("A zero-delay stop resurrected after relaunch")
                }
                emit("NVPN_IOS_RELEASE_ZERO_DELAY_RELAUNCH_PASSED=1")
            }
            try requireStableDirectSource(
                spec.sourceIpUrl,
                expected: directSource,
                duration: 1
            )
            try NostrVpnReleaseNetworkProbe.requireControlledHTTPUnavailable(
                spec.resolverProbeUrl
            )
            emit(
                "NVPN_IOS_RELEASE_RAPID_STOPPED_\(cycle)_MS="
                    + "\(millisecondsSinceEpoch())"
            )
        }

        // A stale asynchronous start can otherwise appear disconnected long
        // enough for a single probe to pass and then resurrect the tunnel.
        try requireStableDirectSource(
            spec.sourceIpUrl,
            expected: directSource,
            duration: 5
        )
    }

    private func requireStableDirectSource(
        _ sourceIpUrl: String,
        expected: String,
        duration: TimeInterval
    ) throws {
        let deadline = Date().addingTimeInterval(duration)
        repeat {
            try NostrVpnReleaseNetworkProbe.requireSourceIP(
                sourceIpUrl,
                expected: expected
            )
            guard waitForVPNState(on: false, timeout: 0) else {
                throw gateError("A stopped Release tunnel became enabled again")
            }
            Thread.sleep(forTimeInterval: 0.2)
        } while Date() < deadline
    }

    func proveExit(_ spec: Spec, label: String) throws {
        try NostrVpnReleaseNetworkProbe.exerciseFreshDNSQuery(
            baseHost: spec.resolverQueryHost
        )
        try NostrVpnReleaseNetworkProbe.requireDNSURL(
            spec.resolverProbeUrl,
            expectedBody: spec.resolverExpectedBody
        )
        try NostrVpnReleaseNetworkProbe.requireUDPEcho(
            host: spec.udpHost,
            port: spec.udpPort,
            label: "\(spec.caseName)-\(label)"
        )
        try NostrVpnReleaseNetworkProbe.requirePublicHTTPS(spec.publicHttpsUrl)
        try NostrVpnReleaseNetworkProbe.requireSourceIP(
            spec.sourceIpUrl,
            expected: spec.expectedExitSourceIp
        )
        emit("NVPN_IOS_RELEASE_EXTERNAL_EXIT_PROBE=\(label)")
    }

    private func proveDirect(_ spec: Spec, expectedSource: String) throws {
        try NostrVpnReleaseNetworkProbe.requireDNSResolution(spec.publicHttpsUrl)
        try NostrVpnReleaseNetworkProbe.requirePublicHTTPS(spec.publicHttpsUrl)
        try waitForSourceIP(
            spec.sourceIpUrl,
            expected: expectedSource,
            timeout: 15
        )
        try NostrVpnReleaseNetworkProbe.requireControlledHTTPUnavailable(
            spec.resolverProbeUrl
        )
    }

    private func driveBackgroundForeground(_ spec: Spec) throws {
        for cycle in 1...spec.lifecycleCycles {
            let started = Date()
            emit("NVPN_IOS_RELEASE_BACKGROUND_\(cycle)_REQUESTED_MS=\(millisecondsSinceEpoch())")
            XCUIDevice.shared.press(.home)
            Thread.sleep(forTimeInterval: 16)
            try NostrVpnReleaseNetworkProbe.requireSourceIP(
                spec.sourceIpUrl,
                expected: spec.expectedExitSourceIp
            )
            try NostrVpnReleaseNetworkProbe.requireUDPEcho(
                host: spec.udpHost,
                port: spec.udpPort,
                label: "\(spec.caseName)-background-\(cycle)"
            )
            let remaining = TimeInterval(spec.backgroundDwellSeconds)
                - Date().timeIntervalSince(started)
            if remaining > 0 {
                Thread.sleep(forTimeInterval: remaining)
            }
            app.activate()
            guard waitForApplicationState(.runningForeground, timeout: 10),
                  waitForVPNState(on: true, timeout: 8)
            else {
                throw gateError("Release app/VPN did not survive lifecycle cycle \(cycle)")
            }
            try proveExit(spec, label: "foreground-\(cycle)")
            emit("NVPN_IOS_RELEASE_FOREGROUND_\(cycle)_VERIFIED_MS=\(millisecondsSinceEpoch())")
        }
    }

    private func driveConfigSyncBackgroundForeground(
        _ spec: Spec,
        directSource: String
    ) throws {
        openInternetTab()
        let save = scrollToElement("wireguard-save")
        guard save.isEnabled, save.isHittable else {
            throw gateError("Shipped WireGuard Save control was unavailable")
        }

        // Autoconnect is disabled through the shipped Settings toggle in test
        // setup. The Reconnecting phase is emitted by production code only
        // after the old PacketTunnel has confirmed it is disconnected.
        save.tap()
        let status = element("internet-settings-status")
        let deadline = Date().addingTimeInterval(4)
        while Date() < deadline,
              !status.label.localizedCaseInsensitiveContains("Reconnecting VPN")
        {
            Thread.sleep(forTimeInterval: 0.02)
        }
        guard status.label.localizedCaseInsensitiveContains("Reconnecting VPN") else {
            throw gateError("Live WireGuard replacement did not confirm disconnection")
        }

        emit("NVPN_IOS_RELEASE_CONFIG_BACKGROUND_REQUESTED_MS=\(millisecondsSinceEpoch())")
        XCUIDevice.shared.press(.home)
        let backgroundDeadline = Date().addingTimeInterval(4)
        while Date() < backgroundDeadline,
              app.state != .runningBackground,
              app.state != .runningBackgroundSuspended
        {
            Thread.sleep(forTimeInterval: 0.02)
        }
        guard app.state == .runningBackground
                || app.state == .runningBackgroundSuspended
        else {
            throw gateError("Release app did not enter the background during config sync")
        }
        try waitForSourceIP(
            spec.sourceIpUrl,
            expected: directSource,
            timeout: 15
        )
        try NostrVpnReleaseNetworkProbe.requireControlledHTTPUnavailable(
            spec.resolverProbeUrl
        )
        emit("NVPN_IOS_RELEASE_CONFIG_BACKGROUND_DIRECT=1")

        app.activate()
        guard waitForApplicationState(.runningForeground, timeout: 10),
              waitForVPNState(on: true, timeout: 10)
        else {
            throw gateError("VPN-on intent did not recover after interrupted config sync")
        }
        openInternetTab()
        assertPicker("internet-source-picker", contains: "WireGuard VPN")
        try waitForSourceIP(
            spec.sourceIpUrl,
            expected: spec.expectedExitSourceIp,
            timeout: 20
        )
        try proveExit(spec, label: "config-sync-foreground")
        emit("NVPN_IOS_RELEASE_CONFIG_BACKGROUND_RECOVERED=1")
    }

    private func selectDirectWhileConnected(
        _ spec: Spec,
        directSource: String
    ) throws {
        openInternetTab()
        scrollToElement("internet-source-picker").tap()
        let direct = element("internet-source-direct")
        guard direct.waitForExistence(timeout: 3), direct.isHittable else {
            throw gateError("Shipped This device choice was unavailable")
        }
        direct.tap()
        // Interrupt the scheduled stop/restart immediately after the desired
        // Direct setting is persisted. Cold startup must compare the installed
        // manager's route shape with the desired provider configuration.
        relaunch()
        openInternetTab()
        assertPicker("internet-source-picker", contains: "This device")
        guard waitForVPNState(on: true, timeout: 8) else {
            throw gateError("This device relaunch stopped the private-mesh packet tunnel")
        }
        try proveDirect(spec, expectedSource: directSource)
        emit("NVPN_IOS_RELEASE_CONNECTED_DIRECT_PASSED=1")
        // The external black-box sampler must observe the unchanged extension
        // process after Direct has taken effect while the OS VPN stays active.
        Thread.sleep(forTimeInterval: 6)
    }

    private func releaseSpec() throws -> Spec {
        let environment = ProcessInfo.processInfo.environment
        guard environment["NVPN_XCUITEST_RELEASE_NETWORK_GATE"] == "1" else {
            throw gateError("Release network gate environment was not armed")
        }
        guard let encoded = environment["NVPN_XCUITEST_RELEASE_NETWORK_SPEC_BASE64"],
              let data = Data(base64Encoded: encoded)
        else {
            throw gateError("Release network spec was missing or invalid")
        }
        return try JSONDecoder().decode(Spec.self, from: data)
    }

    private func optionalReleaseSpec() -> Spec? {
        let encoded = ProcessInfo.processInfo.environment[
            "NVPN_XCUITEST_RELEASE_NETWORK_SPEC_BASE64"
        ]
        guard let encoded,
              let data = Data(base64Encoded: encoded)
        else {
            return nil
        }
        return try? JSONDecoder().decode(Spec.self, from: data)
    }

    private func validate(_ spec: Spec) throws {
        guard !spec.runId.isEmpty,
              spec.runId.range(
                of: #"^[a-zA-Z0-9._-]+$"#,
                options: .regularExpression
              ) != nil
        else {
            throw gateError("Release gate run ID is invalid")
        }
        guard !spec.caseName.isEmpty,
              !spec.networkName.isEmpty,
              spec.wireGuardConfig.contains("[Interface]"),
              spec.wireGuardConfig.contains("[Peer]"),
              !spec.resolverQueryHost.isEmpty,
              !spec.resolverProbeUrl.isEmpty,
              !spec.udpHost.isEmpty,
              !spec.publicHttpsUrl.isEmpty,
              !spec.sourceIpUrl.isEmpty,
              !spec.expectedExitSourceIp.isEmpty
        else {
            throw gateError("Release network spec was incomplete")
        }
        guard (1...3).contains(spec.lifecycleCycles),
              (16...60).contains(spec.backgroundDwellSeconds),
              (5...45).contains(spec.underlayAssociationTimeoutSeconds)
        else {
            throw gateError("Release lifecycle or underlay bounds were invalid")
        }
        if spec.mode == "encrypted", spec.provider == "custom" {
            guard spec.customUrl.hasPrefix("https://"), !spec.bootstrapIps.isEmpty else {
                throw gateError("Custom DoH case was incomplete")
            }
        }
        if spec.mode == "through_exit", spec.throughExitServers.isEmpty {
            throw gateError("Through-exit DNS case had no server")
        }
    }

    func millisecondsSinceEpoch() -> Int64 {
        Int64(Date().timeIntervalSince1970 * 1_000)
    }

    func emit(_ marker: String) {
        PhysicalGateMarker.emit(marker)
    }

    func gateError(_ message: String) -> NSError {
        NSError(
            domain: "NostrVpnReleaseNetworkGate",
            code: 1,
            userInfo: [NSLocalizedDescriptionKey: message]
        )
    }
}
