FROM ubuntu:24.04

ARG RUST_TOOLCHAIN=1.95.0

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      build-essential \
      ca-certificates \
      curl \
      dpkg-dev \
      fakeroot \
      file \
      git \
      libadwaita-1-dev \
      libclang-dev \
      libdbus-1-dev \
      libgtk-4-dev \
      libssl-dev \
      musl-tools \
      pkg-config \
      python3 \
      xz-utils \
    && rm -rf /var/lib/apt/lists/*

ENV RUSTUP_HOME=/opt/rustup
ENV CARGO_HOME=/opt/cargo
ENV PATH=/opt/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN curl --proto '=https' --tlsv1.2 --fail --silent --show-error \
      https://sh.rustup.rs \
      | sh -s -- -y --profile minimal --default-toolchain "${RUST_TOOLCHAIN}" \
    && rustc --version \
    && cargo --version

RUN rustup target add x86_64-unknown-linux-musl \
    && cargo install cargo-deb --version 3.7.0 --locked \
    && cargo deb --version

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc

WORKDIR /workspace/app
